Initial commit
connected-world-services/more-promises pull request #1
Opened 2017-02-16 23:36 UTC by fidian

Here's the library I've been promising.

2017-02-16 23:43 UTC, fidian commented
Added a fudge factor to times that allow the tests to pass on Node 4. Looks like a `setTimeout(function, 100)` might get called only 99 ms later.

2017-02-17 13:49 UTC, GoogilyBoogily requested changes

2017-02-17 13:49 UTC, GoogilyBoogily commented on CHANGELOG.md
> +1.0.0 - YYYY-MM-DD
Should probably have today's date.

2017-02-17 13:49 UTC, GoogilyBoogily commented on spec/lib/index.spec.js
> +     * @param {boolean} [isFailure=false]
Doesn't look like isFailure actually defaults to `false`. Granted, `undefined` and `false` are treated the same way, but technically, there is a difference.

2017-02-17 13:53 UTC, fidian commented on CHANGELOG.md
> +1.0.0 - YYYY-MM-DD
Corrected. 60cbb5e

2017-02-17 14:00 UTC, GoogilyBoogily approved these changes
Looks good to me.

2017-02-17 14:45 UTC, merged